### ISSUE TITLE
support for solver with direct model?

### ISSUE THREAD

**Issue by xhub** [JuliaOpt/MINLPTests.jl#24]
Right now the tests only work with a solver specified as an `optimizer_factory` for a `JuMP.Model` call.
This precludes using this nice package with a solver in direct mode.

Is it planned to support specifying the solver in direct mode?
My guess is that the main hurdle is that one needs to use `JuMP.direct_model` to create such solver, rather than `JuMP.Model`.

**Comment by ccoffrin** [comment]
As I understand it, any solver that supports direct mode should also support the cacheing mode that is used in these tests.

Thoughts @odow, @blegat?

**Comment by odow** [comment]
> any solver that supports direct mode should also support the cacheing mode that is used in these tests.

Correct. What is the motivation for testing in direct mode?

**Comment by xhub** [comment]
To test the direct mode codepath :)

Any solver would be able to use this package via any mode, I would find it nice to be able to also test the direct mode. Nothing critical, would just be nice to have. "No" is a perfectly fine answer

**Comment by odow** [comment]
Which solver? Have you implemented a specialized `copy_to` in addition to the direct interface?

**Comment by ccoffrin** [comment]
I think it would be in scope of this repo to add one "direct mode" test to the suite.  Thoughts on that @odow?

**Comment by xhub** [comment]
https://github.com/xhub/ReSHOP.jl

I did not implement a `copy_to`.
I was playing with `direct_model` a few month ago and I was struggling to find what should be implemented for the direct interface. So I was looking to do some TDD, and this repo is quite nice for that purpose. Maybe things have changed in the documentation, would love to learn more about it (on the proper channel? drifting towards offtopic I feel :))

**Comment by odow** [comment]
Since you have this line:
https://github.com/xhub/ReSHOP.jl/blob/f42d87d0f4bf96339e2377b4520477340224bfc4/src/MOI_wrapper.jl#L129-L132
the current tests will have the same coverage as if you used `direct_mode`. 

`Model(optimizer)` results in the following steps:
- Build model in JuMP
- Call `copy_to` to `optimizer`
- If specialized `copy_to` exists, call that (e.g., Clp builds the entire A matrix and calls loadProblem: https://github.com/JuliaOpt/Clp.jl/blob/dfb2c475788f86dafb7f7ce2849c1957ebc4a638/src/MOI_wrapper/MOI_wrapper.jl#L238-L280)
- Otherwise, fallback to incremental build via `add_variable` and `add_constraint`.

Direct mode skips the JuMP cache and `copy_to`, and goes straight to `add_variable` and `add_constraint`.

I don't think we need any changes to `MINLPTests.jl`.

**Comment by xhub** [comment]
It dates back from February, but this is what I recall. When playing with `direct_model`, I ended up implementing some functions, like `function MOI.get(model::Optimizer, loc::MOI.ListOfConstraints)` or `MOI.is_valid(model::Optimizer, ci::MOI.ConstraintIndex)` which are not required for a classical MOI solver. For instance KNITRO has no `MOI.is_valid`, and is (I believe) fully functional as a solver. By looking at MOSEK, I saw a `MOI.transform` that I may want to also add. So coverage with in direct model is higher.

Correct me if I am wrong, but it is not documented which functions needs to be implemented so I was just trying with some toy models. Hence, the TDD approach. There is an extensive list in `apireference.md`, it would be great to just have a table of functions that needs to be implemented for a complete direct interface

**Comment by odow** [comment]
If KNITRO doesn't implement `MOI.is_valid`, then that is a bug.

In fact, it looks like it is missing a lot of the interface, because most tests are excluded:
https://github.com/JuliaOpt/KNITRO.jl/blob/60d24774ca1ed9f998c572d35988c2ff23468ab3/test/MOI_wrapper.jl#L68-L82

and it doesn't implement 
```Julia
MOI.Test.basic_constraint_tests(model, config)
```
or
```julia
MOI.Test.unittest(model, config)
```

If ReSHOP passed the following, plus MINLPTests, you're doing pretty well:
```julia
MOI.Test.unittest(model, config)
MOI.Test.basic_constraint_tests(model, config)
MOI.Test.contlineartest(model, config)
```

**Comment by xhub** [comment]
Thanks for the pointers, I didn't have
```julia
MOI.Test.unittest(model, config) 
MOI.Test.basic_constraint_tests(model, config)
```

and I am still skipping some tests in `contlineartest`, will work on that.

Closing since the MOIT seems to cover quite a lot already
